import type { Dessert, Review } from './types'

// The sprite sheet is 4x2 grid (4 columns, 2 rows) from the cupcake.png image
// Row 0: strawberry, cupcake, donut, shortcake
// Row 1: macaron, strawberry tart, birthday cake, swiss roll

export const desserts: Dessert[] = [
  {
    id: 1,
    name: 'Stroberi Segar',
    emoji: '🍓',
    description: 'Stroberi manis segar langsung dari kebun, penuh vitamin C dan rasa cinta!',
    price: 15000,
    spriteX: 0,
    spriteY: 0,
    tags: ['segar', 'buah', 'favorit'],
    calories: 45,
    rating: 4.8,
    available: true,
    color: '#ff6b9d',
  },
  {
    id: 2,
    name: 'Cupcake Krim',
    emoji: '🧁',
    description: 'Cupcake fluffy dengan topping whipped cream dan hiasan stroberi mini yang menggemaskan!',
    price: 25000,
    spriteX: 1,
    spriteY: 0,
    tags: ['kue', 'krim', 'manis'],
    calories: 280,
    rating: 5.0,
    available: true,
    color: '#ffb3cc',
  },
  {
    id: 3,
    name: 'Donat Pink',
    emoji: '🍩',
    description: 'Donat empuk dengan glazing pink strawberry dan taburan sprinkles warna-warni!',
    price: 20000,
    spriteX: 2,
    spriteY: 0,
    tags: ['donat', 'glazing', 'warna'],
    calories: 320,
    rating: 4.7,
    available: true,
    color: '#ff85ad',
  },
  {
    id: 4,
    name: 'Shortcake Klasik',
    emoji: '🍰',
    description: 'Shortcake tradisional berlapis krim putih lembut dengan stroberi segar di atasnya.',
    price: 35000,
    spriteX: 3,
    spriteY: 0,
    tags: ['kue', 'klasik', 'premium'],
    calories: 390,
    rating: 4.9,
    available: true,
    color: '#ffd6e7',
  },
  {
    id: 5,
    name: 'Macaron Sakura',
    emoji: '🌸',
    description: 'Macaron Prancis berwarna peach lembut dengan isian buttercream rasa sakura yang harum!',
    price: 30000,
    spriteX: 0,
    spriteY: 1,
    tags: ['macaron', 'prancis', 'harum'],
    calories: 220,
    rating: 4.6,
    available: true,
    color: '#ffc8a0',
  },
  {
    id: 6,
    name: 'Tart Stroberi',
    emoji: '🫐',
    description: 'Tart renyah berisi custard vanilla creamy, ditaburi stroberi segar yang melimpah!',
    price: 40000,
    spriteX: 1,
    spriteY: 1,
    tags: ['tart', 'custard', 'premium'],
    calories: 350,
    rating: 4.9,
    available: true,
    color: '#ff4d7d',
  },
  {
    id: 7,
    name: 'Birthday Cake',
    emoji: '🎂',
    description: 'Kue ulang tahun mini dengan 3 lapisan krim dan dekorasi stroberi di atas yang mewah!',
    price: 55000,
    spriteX: 2,
    spriteY: 1,
    tags: ['ulang tahun', 'spesial', 'mewah'],
    calories: 480,
    rating: 5.0,
    available: true,
    color: '#e8a4c8',
  },
  {
    id: 8,
    name: 'Swiss Roll',
    emoji: '🍥',
    description: 'Swiss roll lembut dengan isian krim stroberi yang digulung sempurna — klasik dan elegan!',
    price: 38000,
    spriteX: 3,
    spriteY: 1,
    tags: ['roll', 'krim', 'elegan'],
    calories: 310,
    rating: 4.8,
    available: true,
    color: '#ffc4d6',
  },
]

export const reviews: Review[] = [
  {
    id: 1,
    author: 'Putri Andini',
    avatar: '👩‍🦱',
    text: 'Cupcake-nya enak banget! Krimnya lembut dan manis pas. Pasti balik lagi! 💕',
    rating: 5,
    date: '2 hari lalu',
  },
  {
    id: 2,
    author: 'Rizky Pratama',
    avatar: '👨‍🍳',
    text: 'Swiss roll-nya juara! Teksturnya sempurna dan rasanya ga terlalu manis. Recommended!',
    rating: 5,
    date: '4 hari lalu',
  },
  {
    id: 3,
    author: 'Siti Rahayu',
    avatar: '👩‍🦰',
    text: 'Donat pink-nya lucu banget dan enak! Cocok banget buat hadiah. Kemasannya juga aesthetic 🌸',
    rating: 4,
    date: '1 minggu lalu',
  },
  {
    id: 4,
    author: 'Budi Santoso',
    avatar: '🧑‍💼',
    text: 'Pesan birthday cake buat istri, dia langsung suka! Dekorasinya cantik dan rasanya premium.',
    rating: 5,
    date: '1 minggu lalu',
  },
]
